### PR TITLE
More complete stop words (from Veronis)

### PR DESCRIPTION
**Pull request by fuhrmanator**
See http://clu.uni.no/corpora/1999-1/0042.html and http://voyant-tools.org/tool/Cirrus/ for the reference to Veronis source of stop words.

I'm not entirely sure about how StopWords.java will treat the apostrophes in the words, or if I should have forked the vcl-xx source to make the change there.

### CODE REVIEW

**Comment by jdf** [comment]
Most of those do not look like stop words to me. Numbers?

**Comment by fuhrmanator** [comment]
Some are numbers (spelled out), some are common abbreviations, some are (subjunctive, passé simple) tenses of helping verbs, some are conjunctions, some are common units, etc. The list comes from a linguistics professor in France, so I'm willing to give it the benefit of the doubt. http://clu.uni.no/corpora/1999-1/0042.html

I realize there are some words with underscores, which will not match (based on the code I saw in java), so maybe they should be skipped. I think the goal there was something like if you had the expression "matter of fact" appearing in English, the whole thing would be removed as a "stop phrase" (something that's commonly written or said, but that shouldn't be parsed for a word cloud.

**Comment by jdf** [comment]
Only individual words are considered during stop-word removal. Underscores will never match.

**Comment by fuhrmanator** [comment]
It's two lines which already have individual entries: 
plus_d'un
plus_d'une

Do you want to reject and I re-patch, removing those two? (sorry, I'm not so smooth with the PR process on GitHub).

**Pull request merged**
